# Generated by Django 3.2.16 on 2023-05-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='for_post',
        ),
    ]
